### ISSUE TITLE
Alleyway - Player doesn't move left+right at game start

### ISSUE THREAD

**Issue by nmclaren** [JoseJX/analogue-pocket-patches#5] opened 2021-12-31 21:55 UTC
Tried the fixed ips patch for Alleyway. Started a new game, LEFT+RIGHT controls do not work after starting a new game.

**Comment by JoseJX** [comment] 2022-01-01 02:15
I can't reproduce this, can you make sure that you've done the following:

- Make sure you've upgraded to v1.0a, it fixes some input issues
- If you haven't upgraded to v1.0a, try completely power cycling the Pocket, it can fix the input problem
- Make sure that the ROM MD5 matches the one listed on the page. If the MD5 sum differs, it won't work right

Thanks!

**Comment by nmclaren** [comment] 2022-01-01 02:23
md5sums of all relevant files:
91128778a332495f77699eaf3a37fe30  Alleyway (World).gb
58fc646a6b441d0a3970d8e60007301c  Alleyway.gb << patched ROM (before renaming to .pocket)
9fb49a87f68a4c8e6af739737ff2f869  Alleyway.ips

- I have upgraded to 1.0a prior to starting testing originally.
- I tested with a cold boot (I never suspend to begin with) and subsequently Quit Game then launched Tetris and Tetris DX where LEFT+RIGHT work correctly.
- To clarify, I can reproduce this every time and have recorded a video showing so if that helps.

**Comment by JoseJX** [comment] 2022-01-01 02:51
Okay, I'd be happy to see the video, but I've tried a few times and can't reproduce here. My MD5's all match yours, so that's not it. Unfortunately, it's going to be hard to figure out if I can't reproduce here.

**Comment by nmclaren** [comment] 2022-01-01 03:04
What am I missing? Lol! https://www.dropbox.com/s/jppp8ryojnq0u0d/Video%20Dec%2031%2C%206%2021%2023%20PM.mov?dl=0

**Comment by JoseJX** [comment] 2022-01-01 03:25
Yeah, I'm not sure, I really can't see anything wrong there, although it does appear that the left button is pressed right away when the game starts.

Maybe check that your SD card isn't silently corrupting the ROM? Try with another SD card, a different cluster size, etc.? Or keep the file on the SD card, but make a new copy from the IPS and copy that to another name, Alleyway2.pocket (or something).

Do you have the real cart? Does it do the same thing?

I'm kind of running out of ideas here :(

**Comment by JoseJX** [comment] 2022-01-06 17:50
I'm going to close this, I've had a few other people test the ROM and it looks okay. Let me know if you figure out another way to reproduce this!

**Closed as completed by JoseJX** 2022-01-06 17:50 UTC
