### ISSUE TITLE
INFGMB.ips - Can't Get Games to Play

### ISSUE THREAD

**Issue by ftalligator** [JoseJX/analogue-pocket-patches#12] opened 2022-01-07 00:19 UTC
First off, thank you so much for taking the initiative to make this available. Much appreciated!

I'm not able to get any of my z3 files to work with this patch. No matter which source I try, I always get a blank screen with the environment's frame around it, but no game loads. I've attached a screen shot of what that looks like for reference.

Let me know if there is something different I should be trying that could get this working. I'm very interested in getting this up and running and providing any feedback or input that would be useful in getting this issue resolved. 

Thank you, 

- FTAlligator

![IMG_2617](https://user-images.githubusercontent.com/41794685/148470708-c90a26f5-4618-481e-b114-c41a372dd502.png)

**Comment by JoseJX** [comment] 2022-01-07 04:06
This was a bug on my end! The game intentionally is sized for 256K so that it can fit the Z-Machine game at the end of the parser. However, I neglected to trim the extra off the end of the ROM after I had re-compiled it before I prepared the IPS patch. So, the end result was that it was trying to load the game, but it was just empty space.

I've redone the patch, please give it a try and let me know if you have any other issues! And let me know what your first Z-Machine game you play will be! :) Mine was HHG2G, lots of fond memories there. My first ever Z-Machine game was Wishbringer, but that was a long time ago.

Enjoy and sorry for the trouble.

**Comment by treyturner** [comment] 2022-01-07 17:16
I had this same problem but decided I had enough things to do already and didn't want to chase it down any further.

So when I saw the patch fix I tried it; games still lock up on boot, though now it says 'PANIC' at the bottom.

Disclaimer: I haven't done a lot of additional troubleshooting here, but I'm pretty sure I'm creating the .pockets correctly (via `copy /B INFGMB.pocket + game.z3 game.pocket`. They're the filesize I expect at least.

**Comment by ftalligator** [comment] 2022-01-07 17:28
I see the PANIC error as well except with my **Zork I** attempt which displays the screen captured below.

And I'm really looking forward to playing **HHGttG** and maybe even the Scott Adams games which are in Z5 format. :) 

![IMG_2618](https://user-images.githubusercontent.com/41794685/148582744-68b30c0e-73c1-43bc-893c-903b2c50b882.png)

**Comment by JoseJX** [comment] 2022-01-07 21:55
I will look into this again later tonight, sorry for the trouble!

**Comment by ftalligator** [comment] 2022-01-11 12:08
Just checking in to see if there are any updates available on this patch. If I can be of any assistance testing or reviewing anything, just let me know. 

Thanks!

**Comment by JoseJX** [comment] 2022-01-11 15:16
Not yet. I can't reproduce the issue in an emulator, which would help a lot for debugging. I'll let you know if I have any ideas on this.

Tested:

- Works on EZ-Flash Jr with original ROM
- Works on Sameboy Emulator with both original ROM and pocket file
- Doesn't work correctly on .pocket file on Analogue HW
- Not fixed by Firmware 1.0b

I redid the patch and traced all STAT/LCDC accesses. Something must be wrong with the way I'm generating the ROM.

Next step will be to use my build system to generate an unpatched ROM and make sure that still works on EZ-Flash Jr to rule out issues with the build system itself (i.e. wrong ROM type or something).

The result of the above is that the build process is wrong for this ROM. I'm going to dig into it a bit and try to reproduce the original from the sources. If that doesn't work, I'll manually produce the IPS patch without decompiling the ROM.

**Comment by JoseJX** [comment] 2022-02-01 19:53
I have some good news! I was finally able to figure out what was wrong with the build system. Basically, it was truncating the ROM size in the header, which was incorrect. I guess the emulators are more forgiving about header errors than the Pocket.

In any case, I tried it with Wishbringer and HHG2G and both worked fine now. Sorry for the amount of time this took to figure out!

Also, just to be clear, this only works with z1,z2 and z3 games, newer formats are unfortunately not supported.

**Closed as completed by JoseJX** 2022-02-01 19:53 UTC

**Comment by ftalligator** [comment] 2022-02-01 20:31
TY! I got HHGttG working! :)

**Comment by JoseJX** [comment] 2022-02-01 20:37
Awesome! Enjoy!
